### ISSUE TITLE
Meet - NullPointerException

### ISSUE THREAD

**Issue by alexbainbridge** [FurhatRobotics/example-skills#38]
Using mac desktop launcher 2.5.0

1. Create new skill based on meet
2. Run skill from IDE (no changes)
3. Put a user into the zone. On entry errors with a NullPointerException. Skill stops running

```
14:19:32 [Skill: 8775] INFO  Skill:137 - Connecting to Furhat server on 0.0.0.0:1932
14:19:32 [MeetFurhatSkill: 8775] INFO  MeetFurhatSkill:164 - Starting skill
14:19:32 [EventSystem: 8775] WARN  FurhatSpeech:150 - Cannot find voice MonicaNeural (en-US) - Microsoft Azure
14:19:33 [MeetFurhatSkill: 8775] WARN  JsonDialogLogger:373 - The directory provided does not end with a trailing directory separator:
14:19:33 [Broker Client: 8775] WARN  Event:194 - Could not set field azureUseProvisioned with type class java.lang.Boolean on builder class furhatos.event.responses.ResponseRecognizer$Builder : null
14:19:33 [Broker Client: 8775] WARN  Event:196 - Verify that the SDK/Robot and Skill have the same version of furhat-commons
14:19:33 [Broker Client: 8775] WARN  Event:194 - Could not set field azureRegionProvisioned with type class java.lang.String on builder class furhatos.event.responses.ResponseRecognizer$Builder : null
14:19:33 [Broker Client: 8775] WARN  Event:196 - Verify that the SDK/Robot and Skill have the same version of furhat-commons
We are in United Kingdom
14:19:41 [furhatos.flow.kotlin.FlowControlRunner$parallel$2: 8775] WARN  Flow: 94 - Flow unknown - parallel unresponsive, 5411 ms since last event poll
java.lang.NullPointerException
	at furhatos.flow.kotlin.Furhat$sayState$1.invoke(Furhat.kt:485)
	at furhatos.flow.kotlin.Furhat$sayState$2$1.invoke(Furhat.kt:553)
```
Much more error log on the NullPointerException

**Comment by alexbainbridge** [comment]
Likely to be an issue where Polly voices were (temporarily?) unavailable, and this is not handled within the example skill.

Closing
